### ISSUE TITLE
ofd户型图显示不出

### ISSUE THREAD

**Issue by llfgit** [11627685/EasyOFD#1]

**Comment by 11627685** [comment]
户型图的ofd文件？你最好上传一下原始文件。

**Comment by 11627685** [comment]
> _No description provided._

户型图的ofd文件？你最好上传一下原始文件。

**Comment by llfgit** [comment]
这里不支持上传ofd文件上来

**Comment by llfgit** [comment]
[分户图2_1.OFD.pdf](https://github.com/11627685/EasyOFD/files/14416123/2_1.OFD.pdf)
后缀名改一下ofd

**Comment by 11627685** [comment]
1.0.7版本已经修复
