### ISSUE TITLE
最大支持体积多少？

### ISSUE THREAD

**Issue by tenglongwentian** [11627685/EasyOFD#11]
最大支持体积多少？

**Comment by 11627685** [comment]
你好：
&nbsp; &nbsp; &nbsp; &nbsp; 没有测试过，这个应该和你电脑，浏览器有关，毕竟是在你的前端展示的。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月29日(星期天) 晚上9:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 最大支持体积多少？ (Issue #11)





 
最大支持体积多少？
