### ISSUE TITLE
目前只有单页切换上一页下一页加载，请问如何初始化加载全部页并滚动查看

### ISSUE THREAD

**Issue by panxiaoxiao0823** [11627685/EasyOFD#12]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/ffa606f3-e0ba-497f-ab9f-c120dbafb04d">

**Comment by 11627685** [comment]
你好：
&nbsp; &nbsp; &nbsp; &nbsp;考虑到文件大小，目前没有做多页的展示，滚动查看。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 下午3:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 目前只有单页切换上一页下一页加载，请问如何初始化加载全部页并滚动查看 (Issue #12)





 image.png (view on web)
