### ISSUE TITLE
IE浏览器不兼容

### ISSUE THREAD

**Issue by llfgit** [11627685/EasyOFD#3]
![Snipaste_2024-03-01_11-45-11](https://github.com/11627685/EasyOFD/assets/45307587/88a2e529-2ee4-4189-a998-860a3280d0bd)

**Comment by llfgit** [comment]
![Uploading Snipaste_2024-03-01_11-45-11.png…]()

**Comment by 11627685** [comment]
我这里已经没有IE浏览器了，也暂时没有计划兼容IE。
