### ISSUE TITLE
部分ofd文件无法正常显示

### ISSUE THREAD

**Issue by 15010418188** [11627685/EasyOFD#4]
通过接口获取12306返回ofd文件，无法正常显示，
插件源码提示ReferenceError: ofd is not defined
for (i = 0; i < ofd.Template.length; i++) {
                            e = t.Template[i];
                            var r = new rt(this.commonData);
                            r.ParseFromXml(e),
                            this.template.push(r)
                        }

**Comment by 11627685** [comment]
1.0.8版本已经修复
