### ISSUE TITLE
水印显示问题

### ISSUE THREAD

**Issue by igaobingbing** [11627685/EasyOFD#5]
文本水印透明度和颜色显示异常

**Comment by 11627685** [comment]
你好：
&nbsp; &nbsp; 还请提供一下文件。方便问题定位，谢谢。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月27日(星期四) 上午9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 水印显示问题 (Issue #5)





 
文本水印透明度和颜色显示异常

**Comment by igaobingbing** [comment]
使用wps打开显示正常。
[my.zip](https://github.com/user-attachments/files/16008905/my.zip)

**Comment by igaobingbing** [comment]
你好，定位到问题了吗
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月27日 09:53 ***@***.***> ***@***.***>,
***@***.***>主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
你好： 
&nbsp; &nbsp; 还请提供一下文件。方便问题定位，谢谢。 
火柴盒 
***@***.*** 
&nbsp; 
------------------&nbsp;原始邮件&nbsp;------------------ 
发件人: "11627685/EasyOFD" ***@***.***&gt;; 
发送时间:&nbsp;2024年6月27日(星期四) 上午9:41 
***@***.***&gt;; 
***@***.***&gt;; 
主题:&nbsp;[11627685/EasyOFD] 水印显示问题 (Issue #5) 
文本水印透明度和颜色显示异常

**Comment by 11627685** [comment]
你好：
&nbsp; &nbsp; 更新最新版本，最新版本已经修复。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月29日(星期六) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)





 你好，定位到问题了吗
 ---- 回复的原邮件 ----
 ***@***.***&gt;发送日期2024年06月27日 09:53 ***@***.***&gt; ***@***.***&gt;,
 ***@***.***&gt;主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
 你好： 
 &amp;nbsp; &amp;nbsp; 还请提供一下文件。方便问题定位，谢谢。 
 火柴盒 
 ***@***.*** 
 &amp;nbsp; 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "11627685/EasyOFD" ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年6月27日(星期四) 上午9:41 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[11627685/EasyOFD] 水印显示问题 (Issue #5) 
 文本水印透明度和颜色显示异常

**Comment by igaobingbing** [comment]
👍
---- 回复的原邮件 ----
***@***.***>发送日期2024年07月01日 08:58 ***@***.***> ***@***.***>,
***@***.***>主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
你好： 
&nbsp; &nbsp; 更新最新版本，最新版本已经修复。 
火柴盒 
***@***.*** 
&nbsp; 
------------------&nbsp;原始邮件&nbsp;------------------ 
发件人: "11627685/EasyOFD" ***@***.***&gt;; 
发送时间:&nbsp;2024年6月29日(星期六) 中午11:04 
***@***.***&gt;; 
***@***.******@***.***&gt;; 
主题:&nbsp;Re: [11627685/EasyOFD] 水印显示问题 (Issue #5) 
你好，定位到问题了吗 
---- 回复的原邮件 ---- 
***@***.***&gt;发送日期2024年06月27日 09:53 ***@***.***&gt; ***@***.***&gt;, 
***@***.***&gt;主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5) 
你好： 
&amp;nbsp; &amp;nbsp; 还请提供一下文件。方便问题定位，谢谢。 
火柴盒 
***@***.*** 
&amp;nbsp; 
------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
发件人: "11627685/EasyOFD" ***@***.***&amp;gt;; 
发送时间:&amp;nbsp;2024年6月27日(星期四) 上午9:41 
***@***.***&amp;gt;; 
***@***.***&amp;gt;; 
主题:&amp;nbsp;[11627685/EasyOFD] 水印显示问题 (Issue #5) 
文本水印透明度和颜色显示异常

**Comment by igaobingbing** [comment]
你好，问一下官网上的航空行程单和铁路客票 OFD 文件从哪能获取到测试样本？
---- 回复的原邮件 ----
***@***.***>发送日期2024年07月01日 11:17 ***@***.***> ***@***.***>,
***@***.***>主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
Closed #5 as completed.

**Comment by igaobingbing** [comment]
水印显示会遮住原件内容
---- 回复的原邮件 ----
***@***.***>发送日期2024年07月01日 11:17 ***@***.***> ***@***.***>,
***@***.***>主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
Closed #5 as completed.

**Comment by 11627685** [comment]
你好：
&nbsp; &nbsp; &nbsp; &nbsp;如果是块状的被遮住， 查看你的水印的背景颜色是否填充了和透明度。
&nbsp; &nbsp; &nbsp; &nbsp;其他问题，提供原文件。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月30日(星期二) 晚上6:47
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)





 水印显示会遮住原件内容
 ---- 回复的原邮件 ----
 ***@***.***&gt;发送日期2024年07月01日 11:17 ***@***.***&gt; ***@***.***&gt;,
 ***@***.***&gt;主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
 Closed #5 as completed.

**Comment by igaobingbing** [comment]
![image](https://github.com/user-attachments/assets/f84d3032-4c43-4461-af39-226874d69ed1)

[my.zip](https://github.com/user-attachments/files/16435056/my.zip)
有设置透明度为0.3

**Comment by igaobingbing** [comment]
从表现来看，现在使用easy-ofd预览时水印在上层，但是通过wps等ofd预览器会发现水印在下层展示。

**Comment by 11627685** [comment]
已修复，下个版本发布。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月31日(星期三) 上午9:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)





 
从表现来看，现在使用easy-ofd预览时水印在上层，但是通过wps等ofd预览器会发现水印在下层展示。

**Comment by igaobingbing** [comment]
👍，我现在能安装新版吗
---- 回复的原邮件 ----
***@***.***>发送日期2024年08月05日 19:34 ***@***.***> ***@***.***>,
***@***.***>主题Re: [11627685/EasyOFD] 水印显示问题 (Issue #5)
已修复，下个版本发布。 
火柴盒 
***@***.*** 
&nbsp; 
------------------&nbsp;原始邮件&nbsp;------------------ 
发件人: "11627685/EasyOFD" ***@***.***&gt;; 
发送时间:&nbsp;2024年7月31日(星期三) 上午9:36 
***@***.***&gt;; 
***@***.***&gt;;"State ***@***.***&gt;; 
主题:&nbsp;Re: [11627685/EasyOFD] 水印显示问题 (Issue #5) 
从表现来看，现在使用easy-ofd预览时水印在上层，但是通过wps等ofd预览器会发现水印在下层展示。
