### ISSUE TITLE
是否有配置，来控制某个按钮的显示与隐藏，例如：打开。 需求是不需要这个打开按钮

### ISSUE THREAD

**Issue by wyb280960511-wang** [11627685/EasyOFD#6]

**Comment by 11627685** [comment]
你可以通过css，也可以通过js。设置： display: none


<div id="myofdselectButton" class="OfdButton OpenFile" style="
&nbsp; &nbsp; display: none;
"&gt;打开</div&gt;



火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月28日(星期五) 下午3:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 是否有配置，来控制某个按钮的显示与隐藏，例如：打开。 需求是不需要这个打开按钮 (Issue #6)
