### ISSUE TITLE
多个ofd文件切换显示错误

### ISSUE THREAD

**Issue by qichenchang** [11627685/EasyOFD#8]
左侧一个ofd文件列表，点击切换显示的ofd文件，能正常展示，但是文件显示叠加，之前的ofd文件依然在类似做了分页展示，有reset之类的api能处理吗

**Comment by 11627685** [comment]
更新最新版本，该bug已经修复。




火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 下午2:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 多个ofd文件切换显示错误 (Issue #8)





 
左侧一个ofd文件列表，点击切换显示的ofd文件，能正常展示，但是文件显示叠加，之前的ofd文件依然在类似做了分页展示，有reset之类的api能处理吗

**Comment by qichenchang** [comment]
目前是最新版本1.0.9，现在通过循环处理可以实现我的需求

**Comment by qichenchang** [comment]
我使用动态id让每个ofd文件都有自己的独特id也无法解决，我检查了一下html，发现是之前渲染的没有销毁导致，所以希望有一个reset或者destroy
