### ISSUE TITLE
部分ofd文件无法正常显示，但签章显示正常

### ISSUE THREAD

**Issue by nichan-13** [11627685/EasyOFD#9]
无法正常显示文件如下：
[ofd.zip](https://github.com/user-attachments/files/16388977/ofd.zip)

**Comment by 11627685** [comment]
你的模板背景颜色为黑色：
目前还不支持Pattern 底纹。

如下：


     <ofd:PathObject ID="4" Boundary="10 10 277 190" Stroke="false" Fill="true"&gt;
                <ofd:FillColor Value="0 0 0"&gt;
                    <ofd:Pattern Width="10" Height="10"&gt;
                        <ofd:CellContent ID="5"&gt;
                            <ofd:ImageObject ID="6" CTM="10 0 0 10 0 0" Boundary="0 0 10 10" Alpha="230" ResourceID="7"/&gt;
                        </ofd:CellContent&gt;
                    </ofd:Pattern&gt;
                </ofd:FillColor&gt;
                <ofd:AbbreviatedData&gt;M 0 190 L 277 190 L 277 0 L 0 0 C </ofd:AbbreviatedData&gt;
        </ofd:PathObject&gt;










火柴盒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "11627685/EasyOFD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月26日(星期五) 下午4:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[11627685/EasyOFD] 部分ofd文件无法正常显示，但签章显示正常 (Issue #9)





 
无法正常显示文件如下：
 ofd.zip

**Comment by nichan-13** [comment]
好的，感谢
